### ISSUE TITLE
Clean up some stuff leftover from 3.0.0rc

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/jupyter-lsp-feedstock#11]
Wanted to get a release out ASAP, but:

## Housekeeping
- [x] remove old build scripts #12
- [x] restore `pip check` #12

## Nice-to-haves
- [ ] maybe hoist some typo-prone values to jinja variables
- [x] maybe add `jupyter-lsp-latex` (#12)
  - https://github.com/conda-forge/texlab-feedstock/pull/4
- [x] maybe add `jupyter-lsp-python-all` with all the fixins  (#12)
- [ ] consider modifying `install.json` to provide conda-specific uninstall instructions? (I do not know if this is hard or easy so just an idea worth considering)
- [x] capture the built artifacts on azure so they can be inspected: (#12)
  ```yaml
  # conda-forge.yml
  azure:
     store_build_artifacts: true
  ```

**Comment by krassowski** [comment]
- [ ] consider modifying `install.json` to provide conda-specific uninstall instructions?

**Comment by bollwyvl** [comment]
Hoisted the item: what's that file actually do?

**Comment by krassowski** [comment]
It's here to guide users on how to uninstall (or answer "how was it installed?"). If you click on the About button shows the text that we provide.

With the `install.json`:

![with](https://user-images.githubusercontent.com/5832902/103826165-358d2800-506e-11eb-9344-de6770815dbd.gif)

Without (or using developer build this is symlinking rather than installing properly):

![without](https://user-images.githubusercontent.com/5832902/103826195-42118080-506e-11eb-9816-679de504b289.gif)

I guess that the metadata might allow for uninstall from the extension manager in the future but I guess this is a difficult decision with security implications that was postponed.

**Comment by krassowski** [comment]
The docs say that admins who install manually or different distribution channels (conda/pip etc) can override the text to fit the distribution circumstances.

**Comment by bollwyvl** [comment]
cool. got a bunch of other stuff on fire, let's see how some usage of `3.0.0_0` goes, and if we have to fix anything before going too crazy with these things...

**Comment by bollwyvl** [comment]
builds are _actually_ up now...

```
  <title>noarch:add:jupyter-lsp-1.0.0-pyhd8ed1ab_0.tar.bz2</title>
  <title>noarch:add:jupyter-lsp-python-1.0.0-pyhd8ed1ab_0.tar.bz2</title>
  <title>noarch:add:jupyter-lsp-r-1.0.0-pyhd8ed1ab_0.tar.bz2</title>
  <title>noarch:add:jupyterlab-lsp-3.0.0-pyhd8ed1ab_0.tar.bz2</title>
```

**Comment by bollwyvl** [comment]
@krassowski so we still didn't monkey with `install.json`... maybe we just let that one be? Otherwise I don't think the machine is running... unless we don't think the manual step is acceptable vs. having to coordinate two feedstocks.

**Comment by krassowski** [comment]
It's rather nice to have, but not a necessity. If JupyterLab decides to use that for actual uninstall then we sure should follow.

**Comment by bollwyvl** [comment]
I think we close this out now, with only the `install.json` thing remaining, in anticipation of something more dynamic in the 4.x or 5.x line.
